RDKCOM-2383 RDKBCMF-280 usp-pa CCSP_COMPONENT_ID build errors
Updating the SHA1 to fix the usp-pa CCSP_COMPONENT_ID build errors as a result of CcspCommonLibrary/61989:
| ../obuspa-4.1.0-master/src/vendor/vendor.c: In function 'RDK_SetGroup':
| ../obuspa-4.1.0-master/src/vendor/vendor.c:103:43: error: 'CCSP_COMPONENT_ID_ACS' undeclared (first use in this function)
|   103 | #define CCSP_USP_WRITE_ID                 CCSP_COMPONENT_ID_ACS
|       |                                           ^~~~~~~~~~~~~~~~~~~~~
| ../obuspa-4.1.0-master/src/vendor/vendor.c:1461:60: note: in expansion of macro 'CCSP_USP_WRITE_ID'
|  1461 |                                            RDK_SESSION_ID, CCSP_USP_WRITE_ID,
|       |                                                            ^~~~~~~~~~~~~~~~~
| compilation terminated due to -Wfatal-errors.
| Makefile:1937: recipe for target 'src/vendor/obuspa-vendor.o' failed

Reason for change: RDKBCMF-280 usp-pa CCSP_COMPONENT_ID build errors
Test Procedure: None.
Risks: Low.
Signed-off-by: Stephen Barrett <stephen.barrett@accenture.com>

(cherry picked from commit f42a38ca5d7ccd926ef44c2eb8b002137ab38aaf)
Change-Id: I13f5d41dd420dd8545d787a77509574c346e5b58